modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
issueTrackerURL = "https://github.com/Azz-9/Flex-HUD/issues"
license = "${license}"
clientSideOnly = true

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
logoFile = "${icon}"
authors = "${mod_author}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version_range},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"