name: Sync Public Branch

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # nécessaire pour pouvoir pousser correctement
          persist-credentials: false

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Prepare branch for public push
        run: |
          # Crée une branche orpheline (pas d'historique)
          git checkout --orphan public
          # Supprime tous les fichiers de l'index
          git reset --hard
          # Ajoute tous les fichiers sauf le workflow
          git add . ':! .github/workflows/*'
          # Commit unique
          git commit -m "Initial public commit"

      - name: Push to public repo
        run: |
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Azz-9/Flex-HUD.git temp-push:main --force